# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{esperanto}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Semyonov"]
  s.date = %q{2010-01-10}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{rotuka@rotuka.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "esperanto.gemspec",
     "lib/esperanto.rb",
     "lib/esperanto/adaptilo.rb",
     "lib/esperanto/adaptilo/abstrakta.rb",
     "lib/esperanto/adaptilo/abstrakta/morfemiko/bazo.rb",
     "lib/esperanto/adaptilo/abstrakta/morfemiko/vorto.rb",
     "lib/esperanto/core_ext/string.rb",
     "lib/esperanto/core_ext/symbol.rb",
     "lib/esperanto/gramatiko.rb",
     "lib/esperanto/morfemiko.rb",
     "lib/esperanto/morfemiko/afikso.rb",
     "lib/esperanto/morfemiko/finajxo.rb",
     "lib/esperanto/morfemiko/prefikso.rb",
     "lib/esperanto/morfemiko/radiko.rb",
     "lib/esperanto/morfemiko/sufikso.rb",
     "lib/esperanto/morfologio.rb",
     "lib/esperanto/morfologio/finajxvorto.rb",
     "lib/esperanto/morfologio/vorteto.rb",
     "test/helper.rb",
     "test/test_esperanto.rb"
  ]
  s.homepage = %q{http://github.com/rotuka/esperanto}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Esperanta morfologio kaj gramatiko por Rubeno}
  s.test_files = [
    "test/helper.rb",
     "test/test_esperanto.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<abstract>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<abstract>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<abstract>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

